### ISSUE TITLE
note

### ISSUE THREAD

**Issue by SheepTester** [SheepTester/sheeptester.github.io#4]
pls dont look this

need in `sheep.css`:
```css
sheep-text-width::after {
  content: "\000A";
}
```
in `sheep.js` option height as well
